[phases.setup]
nixPkgs = ["nodejs", "coreutils"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd ../client && npm install && npm run build"
]

[phases.build]
cmds = [
  "echo Build completed"
]

[start]
cmd = "cd server && npm start"
git 